### ISSUE TITLE
Compilation Error 

### ISSUE THREAD

**Issue by MyrnaC** [fernandozuher/naoqi_webots#2]
# compiling Inertial_Unit.cpp
./nao/01_sensors/Inertial_Unit.cpp: In member function ‘virtual void Inertial_Unit::update()’:
./nao/01_sensors/Inertial_Unit.cpp:49:17: error: missing template arguments before ‘angles’
     std::vector angles {&angle_X, &angle_Y, &acc_X, &acc_Y, &acc_Z, &gyr_X, &gy
                 ^
./nao/01_sensors/Inertial_Unit.cpp:58:41: error: ‘angles’ was not declared in this scope
         m_filters[i]->append_raw_value(*angles[i]);
                                         ^
/usr/local/webots/resources/Makefile.include:532: recipe for target 'build/release/Inertial_Unit.o' failed
make: *** [build/release/Inertial_Unit.o] Error 1

This error appears when i am trying to compile running make in the naoqi_webots_master folder. I am using Ubuntu 16. Do you have any idea of how to solve it? Thanks

**Comment by fernandozuher** [comment]
Hello, @MyrnaC !

This is pretty easy to solve. Just update your g++ compiler (if you use it) to a version that supports **C++17**.

The error: "missing template arguments before ‘angles’"
    is because it is not specified the type of `std::vector`. For example: `std::vector<float>` ...

Before C++17 you have to specify the type. Since that version, the type can be deducted from the values being initialized  in the vector variable ;-)

Let me know if you solved that.
