### ISSUE TITLE
Naoqi simulator sdk

### ISSUE THREAD

**Issue by Saman-Khan** [fernandozuher/naoqi_webots#3]
I am relatively new to this field. Do u have any idea on how do we access naoqi simulator sdk library packages. They seem to be deprecated. Any alternative for it?

**Comment by fernandozuher** [comment]
@Saman-Khan, I am so sorry for such a delay. I was not notified by email about your question.
Anyway, yes, the naoqi simulator sdk library packages are deprecated since a long time ago.
Unfortunately, the "owner" of NAO robot doesn't care about supporting it.
It is up to you try to do whatever you want with that unstable sdk.
